config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }, format: false

  devise_scope :user do
    authenticated :user do
      root to: redirect('/day_records'), as: :authenticated_root

      patch 'change_current_account/:id', to: 'accounts#change_current', format: false, as: :change_current_account

      resources :day_records, except: [:show], format: false do
        collection do
          get 'async_worked_time', action: :async_worked_time
          get 'export', action: :export
          post 'add_now', action: :add_now
        end
      end

      resources :closures, except: [:show], format: false
    end

    unauthenticated do
      root 'site#index', as: :unauthenticated_root
      get '/obrigado', to: 'site#thank_you', as: :thank_you
      post '/contato', to: 'site#contact', as: :contact, format: false
    end
  end
end

app/models/concerns/day_record/clt_worker_account_manipulable.rb
module DayRecord::CltWorkerAccountManipulable
  extend ActiveSupport::Concern

  def clt_manipulate_balance(balance)
    return unless account.allowance_time
    allowance = (account.allowance_time.hour.hours + account.allowance_time.min.minutes)
    balance.reset if balance.to_seconds <= allowance
  end

  def clt_manipulate_over_diff(diff, worked_hours, index)
    check_straight_hours_violation(diff) if worked_hours && index.odd?
  end

  def add_lunch_time(time)
    return time unless account.lunch_time
    return time unless time_records.size < 3

    sum_times(time, account.lunch_time)
  end

  def forecast_departure_time
    return ZERO_HOUR if time_records.empty? || !reference_date.today?
    rest = calculate_hours(false)

    add_lunch_time(sum_times(time_records.first.time, account.workload, rest))
  end

  def labor_laws_violations
    @violations ||= check_labor_laws_violations
  end

  def check_labor_laws_violations
    {
      overtime: check_overtime_violation,
      straight_hours: @straight_hours_violation
    }
  end

  def check_straight_hours_violation(diff)
    return false unless account.warn_straight_hours
    @straight_hours_violation ||= (diff[:hour].hours + diff[:minute].minutes) > 6.hours
  end

  def check_overtime_violation
    return false unless account.warn_overtime
    total_worked_duration > overtime_duration_limit
  end

  def total_worked_duration
    (total_worked.hour.hours + total_worked.min.minutes)
  end

  def overtime_duration_limit
    (account.workload.hour.hours + account.workload.min.minutes + 2.hours)
  end

end

app/models/day_record.rb
class DayRecord < ActiveRecord::Base
  include AccountManipulable
  extend Enumerize

  enumerize :work_day, in: { yes: 1, no: 0 }, default: :yes
  enumerize :missed_day, in: { yes: 1, no: 0 }, default: :no
  enumerize :medical_certificate, in: { yes: 1, no: 0 }, default: :no

  belongs_to :account
  has_many :time_records, inverse_of: :day_record, dependent: :delete_all, after_remove: :recalculate

  accepts_nested_attributes_for :time_records, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :reference_date
  validates_uniqueness_of :reference_date, scope: :account_id

  validate :future_reference_date

  default_scope -> { order(reference_date: :desc) }

  scope :today, -> { where(reference_date: Date.current) }
  scope :date_range, -> (from, to) { where(reference_date: from..to) }

  after_initialize :set_default_values

  before_save :set_calculated_columns
  after_save :touch_account
  after_save :touch_closure_if_needed

  after_destroy :touch_account

  def total_worked
    @total_worked ||= calculate_total_worked_hours
  end

  def balance
    return @balance if @balance
    @balance = TimeBalance.new

    work_day.yes? ? balance_for_working_day : balance_for_non_working_day

    account_manipulate_balance(@balance)

    @balance
  end

  private

  def balance_for_working_day
    if missed_day.no?
      @balance.calculate_balance(account.workload, total_worked)
    else
      @balance.calculate_balance(account.workload, ZERO_HOUR)
    end
  end

  def balance_for_non_working_day
    if missed_day.no?
      @balance.calculate_balance(ZERO_HOUR, total_worked)
    else
      @balance.reset
    end
  end

  def calculate_total_worked_hours
    return calculated_hours unless reference_date.today? && time_records_odd?

    newest_time = time_records.last

    return ZERO_HOUR if newest_time.nil?

    # sum the difference between last time entry and current time
    # to show up-to-now calculation
    now_diff = Time.diff(newest_time.time, Time.current)
    (calculated_hours + now_diff[:hour].hours) + now_diff[:minute].minutes
  end

  def satisfy_conditions(worked, record_index)
    return true if worked && record_index.odd?
    return true if !worked && record_index.even?
    false
  end

  def future_reference_date
    return unless reference_date
    errors.add(:reference_date, :future_date) if reference_date.future?
  end

  def set_default_values
    self.reference_date ||= Date.current
  end

  def calculate_hours(worked_hours = true)
    total = ZERO_HOUR

    reference_time = time_records.first

    time_records.each_with_index do |time_record, index|
      diff = Time.diff(reference_time.time, time_record.time)
      total = total + diff[:hour].hours + diff[:minute].minutes if satisfy_conditions(worked_hours, index)
      account_manipulate_over_diff(diff, worked_hours, index)
      reference_time = time_record
    end

    total
  end

  def set_calculated_columns
    self.calculated_hours = calculate_hours
    self.time_records_odd = time_records.size.odd?
  end

  def touch_account
    account.touch
  end

  def touch_closure_if_needed
    query = []
    query << '(:date >= start_date  AND :date <= end_date)'
    query << 'start_date = :date OR end_date = :date'
    account.closures.where(query.join(' OR '), date: reference_date).update_all(updated_at: Time.current)
  end

  def recalculate(_)
    set_calculated_columns
    save
  end
end

app/models/day_record/base_export.rb
class DayRecord::BaseExport
  attr_reader :data, :from, :to

  TABLE_HEADER = [
    'Dia',
    'Total',
    'Saldo'
  ]

  def initialize(account, from, to)
    @account = account
    @data = account.day_records.includes(:time_records).where(reference_date: from..to)
    @from = from.strftime('%d/%m/%Y')
    @to = to.strftime('%d/%m/%Y')
    @dynamic_headers = entrance_exits
    @header = TABLE_HEADER.dup.insert(1, @dynamic_headers).flatten
  end

  def generate

  end

  protected

  def entrance_exits
    headers = []

    TimeRecord.max_time_count(@data).times do |index|
      headers << h.get_time_label_from_number(index)
    end

    headers
  end

  def h
    ApplicationController.helpers
  end
end

app/models/day_record/export_pdf.rb
class DayRecord::ExportPdf < DayRecord::BaseExport

  def generate
    pdf
    render
    @pdf.render
  end

  private

  def render
    page_header
    reports_list
  end

  def pdf
    @pdf ||= Prawn::Document.new(page_size: 'A4', page_layout: :landscape, margin: [30, 30, 30, 30])
  end

  def page_header
    pdf.text 'Meu Controle de Ponto',
    size: 25,
    align: :left,
    inline_format: true,
    color: '438eb9'

    pdf.text 'www..com.br | Controle suas horas trabalhadas',
    size: 10,
    align: :left,
    inline_format: true,
    style: :italic

    pdf.text_box "#{@account.name}\n#{from} à #{to}",
    size: 12,
    style: :bold,
    align: :right,
    inline_format: true,
    at: [2, 510]
  end

  def reports_list
    pdf.move_down 20
    options = {
      width: 782,
      row_colors: %w(f5f5f5 FFFFFF),
      header: true
    }

    pdf.table([@header, *table_rows], options) do
      row(0).font_style = :bold
      row(0).background_color = '777777'
      row(0).text_color = 'FFFFFF'
    end
  end

  def table_rows
    rows = []

    balance_sum = parse_days(rows)
    mount_sum_row(rows, balance_sum)

    rows
  end

  def parse_days(rows)
    balance_sum = TimeBalance.new

    data.each do |day|
      mount_day_row(rows, day)
      balance_sum.sum(day.balance)
    end

    balance_sum
  end

  def mount_day_row(rows, day)
    text_balance = day.balance.negative? ? '-' : '+'
    times = day.time_records.collect(&:time).map { |time| time.to_s(:time) }
    times.fill('', (times.size)..(@header.size - 4))

    rows << [
      day.reference_date.strftime('%d/%m/%Y'),
      times,
      h.format_seconds_to_time(day.total_worked),
      { content: "#{text_balance} #{day.balance.to_s}", background_color: day.balance.negative? ? 'f7ecf2' : 'dff0d8' }
    ].flatten

    rows << [ { content: "       Observações: #{day.observations}", colspan: @header.size } ] unless day.observations.blank?
  end

  def mount_sum_row(rows, balance_sum)
    text_balance = balance_sum.negative? ? '-' : '+'

    sum_row = [
      { content: "Saldo Total", colspan: @header.size - 1, font_style: :bold },
      { content: "#{text_balance} #{balance_sum.to_s}", background_color: balance_sum.negative? ? 'f7ecf2' : 'dff0d8', font_style: :bold }
    ]

    rows << sum_row
  end

end

app/models/day_record/export_sheet.rb
class DayRecord::ExportSheet < DayRecord::BaseExport

  def generate
    sheet
    render
    @sheet.to_stream.read
  end

  private

  def render
    @sheet.workbook.add_worksheet(name: "Registros") do |sheet|
      page_header(sheet)
      reports_list(sheet)
    end
  end

  def sheet
    @sheet ||= Axlsx::Package.new
    @sheet.use_shared_strings = true
  end

  def page_header(sheet)
    sheet.add_row @header << 'Observações'
  end

  def reports_list(sheet)
    balance_sum = parse_days(sheet)
    mount_sum_row(sheet, balance_sum)
  end

  def parse_days(sheet)
    balance_sum = TimeBalance.new
    
    data.each do |day|
      balance_sum.sum(day.balance)
      sheet.add_row mount_day_row(day)
    end

    balance_sum
  end

  def mount_day_row(day)
    text_balance = day.balance.negative? ? '-' : '+'
    times = day.time_records.collect(&:time).map { |time| time.to_s(:time) }
    times.fill('', (times.size)..(@header.size - 5))

    [
      day.reference_date.strftime('%d/%m/%Y'),
      times,
      h.format_seconds_to_time(day.total_worked),
      "#{text_balance} #{day.balance.to_s}",
      day.observations.to_s
    ].flatten
  end

  def mount_sum_row(sheet, balance_sum)
    text_balance = balance_sum.negative? ? '-' : '+'
    sum_row = ['Saldo Total']
    sum_row.fill('', (1)..(@header.size - 1))
    sum_row[-2] = "#{text_balance} #{balance_sum.to_s}"
    sheet.add_row sum_row
  end

end

app/models/mongo_model/day_record.rb
class MongoModel::DayRecord
  include Mongoid::Document
  extend Enumerize

  store_in collection: "day_records"

  field :reference_date, type: Date, default: -> { Date.current }
  field :observations, type: String
  field :work_day
  field :missed_day
  field :medical_certificate

  enumerize :work_day, in: { yes: 1, no: 0 }, default: :yes
  enumerize :missed_day, in: { yes: 1, no: 0 }, default: :no
  enumerize :medical_certificate, in: { yes: 1, no: 0 }, default: :no

  belongs_to :account, class_name: MongoModel::Account.to_s
  embeds_many :time_records, class_name: MongoModel::TimeRecord.to_s

  accepts_nested_attributes_for :time_records, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :reference_date
  validates_uniqueness_of :reference_date, scope: :account_id

  default_scope -> { desc(:reference_date) }

  scope :today, -> { where(reference_date: Date.current) }
  scope :date_range, -> (from, to) { where(reference_date: from..to) }


  def total_worked
    @total_worked ||= calculate_total_worked_hours
  end

  def balance
    return @balance if @balance
    @balance = TimeBalance.new

    work_day.yes? ? balance_for_working_day : balance_for_non_working_day

    if account._type == 'CltWorkerAccount' && account.allowance_time
      @balance.reset if @balance.to_seconds <= (account.allowance_time.hour.hours + account.allowance_time.min.minutes)
    end

    @balance.reset if medical_certificate.yes?

    @balance
  end

  private

  def balance_for_working_day
    if missed_day.no?
      @balance.calculate_balance(account.workload, total_worked)
    else
      @balance.calculate_balance(account.workload, ZERO_HOUR)
    end
  end

  def balance_for_non_working_day
    if missed_day.no?
      @balance.calculate_balance(ZERO_HOUR, total_worked)
    else
      @balance.reset
    end
  end

  def calculate_total_worked_hours
    return ZERO_HOUR if time_records.empty?

    sum_current_time_to_total(time_records.last.time, calculate_hours)
  end

  def calculate_hours(worked_hours = true)
    total = ZERO_HOUR

    reference_time = time_records.first

    time_records.each_with_index do |time_record, index|
      diff = Time.diff(reference_time.time, time_record.time)
      total = total + diff[:hour].hours + diff[:minute].minutes if satisfy_conditions(worked_hours, index)
      # account_manipulate_over_diff(diff, worked_hours, index)
      reference_time = time_record
    end

    total
  end

  def satisfy_conditions(worked, record_index)
    return true if worked && record_index.odd?
    return true if !worked && record_index.even?
    false
  end

  def sum_current_time_to_total(last_time_record, total)
    return total unless reference_date.today? && time_records.size.odd?
    now_diff = Time.diff(last_time_record, Time.current)
    (total + now_diff[:hour].hours) + now_diff[:minute].minutes
  end

end

app/controllers/day_records_controller.rb
class DayRecordsController < GenericCrudController
  include ApplicationHelper

  before_action :find_record, only: [:edit, :update, :destroy]
  before_action :set_date_range, only: [:index, :export]

  def index
    all_records = current_account.day_records.includes(:time_records).date_range(@from, @to)
    @day_records = all_records.page params[:page]
    @balance_period = all_records.inject(TimeBalance.new) { |sum_balance, day| sum_balance.sum(day.balance) }
    @max_time_records = TimeRecord.max_time_count(@day_records)
  end

  def new
    @day_record = DayRecord.new
    @day_record.time_records.build
  end

  def create
    @day_record = DayRecord.new(model_params)
    super
  end

  def edit
    @day_record.time_records.build unless @day_record.time_records.exists?
  end

  def update
    super
  end

  def destroy
    super
  end

  def async_worked_time
    set_presenter
    render json: { time: format_seconds_to_time(@account_presenter.total_worked), percentage: @account_presenter.percentage_worked }
  end

  def export

    case export_format_param
    when 'xlsx'
      file_type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      file = DayRecord::ExportSheet.new(current_account, @from, @to)
    else
      file_type = 'application/pdf'
      file = DayRecord::ExportPdf.new(current_account, @from, @to)
    end

    send_data file.generate,
      filename: "#{current_user.first_name} - #{current_user.current_account.name} - #{@from.strftime('%d-%m-%Y')} a #{@to.strftime('%d-%m-%Y')}.#{export_format_param}",
      type: file_type
  end

  def add_now
    current_day = current_account.day_records.today.first_or_create
    current_day.time_records.build(time: Time.current)
    current_day.save

    flash[:success] =  t "day_records.create.success"

    redirect_to action: :index
  end

  private

  def export_format_param
    params.require(:format)
  end

  def set_date_range
    @from = from
    @to = to
  end

  def find_record
    @day_record = current_account.day_records.find(day_record_id_param)
  end

  def day_record_id_param
    params.require(:id)
  end

  def model_params
    params.require(:day_record).
    permit(
      :reference_date, :observations, :work_day, :missed_day, :medical_certificate,
      time_records_attributes: [:id, :time, :_destroy]
      )
  end

  def from
    date_param(params[:from], 30.days.ago)
  end

  def to
    date_param(params[:to])
  end

  def date_param(param, default = Date.current)
    return default if param.blank?
    Time.zone.parse(param).to_date
  rescue ArgumentError
    Rollbar.warning('Formato invalido de data')
    default
  end

end

app/views/day_records/_form.html.erb
<%= simple_form_for day_record do |f| %>
<div class="row">
    <%= f.hidden_field :id %>
    <%= f.input :reference_date, as: :string, wrapper_html: {class: 'col-xs-3 col-md-2 text-center'}, input_html: { value: (localize(f.object.reference_date) if f.object.reference_date), class: 'datepicker text-center'} %>
    <%= f.input :work_day, wrapper_html: {class: 'col-xs-3 col-md-2 text-center'}, label_html: {class: 'col-xs-12'} do %>
      <%= f.input_field :work_day, as: :boolean, class: 'yes-no-checkbox-switch', checked: f.object.work_day == 1  %>
    <% end %>
    <%= f.input :missed_day, wrapper_html: {class: 'col-xs-3 col-md-2 text-center'}, label_html: {class: 'col-xs-12'} do %>
      <%= f.input_field :missed_day, as: :boolean, class: 'yes-no-checkbox-switch', checked: f.object.missed_day == 1 %>
    <% end %>
    <% if current_user.current_account.class == CltWorkerAccount %>
      <%= f.input :medical_certificate, wrapper_html: {class: 'col-xs-3 col-md-2 text-center'}, label_html: {class: 'col-xs-12'} do %>
        <%= f.input_field :medical_certificate, as: :boolean, class: 'yes-no-checkbox-switch', checked: f.object.medical_certificate == 1 %>
      <% end %>
    <% end %>
    <%= f.input :observations, as: :text, wrapper_html: {class: 'col-xs-12 col-md-4'} %>

</div>
<div class="row">
  <h3 class="header blue">Horários <small>Cadastre aqui os horários para este dia</small> </h3>
  <div class="row time-records-container">
    <%= f.fields_for :time_records do |time_record| %>
      <%= render 'time_record_fields', f: time_record %>
    <% end %>

    <div class="col-xs-12 col-md-1 text-center add-container" style="margin-top: 15px;">
      <%= link_to_add_association '<i class="fa fa-plus-circle fa-3x text-success"></i>'.html_safe, f, :time_records,
        {
          'data-association-insertion-node' => '.add-container',
          'data-association-insertion-method' => 'before'
        } %>
    </div>
  </div>
</div>

  <%= f.button :submit, save_and_add_text(f.object), name: 'save_and_add' %>
  <%= f.button :submit %>
<% end %>

app/views/day_records/_labor_law_violation.html.erb
<% if violations[:overtime] %>
<a class="balance-info" tabindex="0" role="button" data-toggle="popover" data-trigger="focus" data-content="Você ultrapassou o limite de 2 horas extras diárias." title="Art. 59 CLT">
  <i class="ace-icon fa fa-exclamation-triangle orange bigger-120"></i>
</a>
<% end %>

<% if violations[:straight_hours] %>
<a class="balance-info" tabindex="0" role="button" data-toggle="popover" data-trigger="focus" data-content="Você trabalhou mais que 6 horas consecutivas sem um período de descanso." title="Art. 71 CLT">
  <i class="ace-icon fa fa-exclamation-triangle orange bigger-120"></i>
</a>
<% end %>

app/views/day_records/_search_range.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="col-xs-12 col-sm-6">
      <%= simple_form_for :date_range, wrapper: :inline_form,
                                       html: { class: 'form-inline row' },
                                       url: day_records_path,
                                       method: :get do |f| %>
      <a href="#" class="btn btn-default btn-sm col-xs-2 hidden-xs" id="daterange-btn">
          <i class="fa fa-calendar"></i> Datas
          <i class="fa fa-caret-down"></i>
      </a>
      <%= f.input :from, input_html: { name: 'from',
                                       value: from.strftime('%d/%m/%Y'), class: 'col-xs-12 text-center' }, wrapper_html: { class: 'col-xs-5 col-sm-4' } %>
      <%= f.input :to, input_html: { name: 'to',
                                     value: to.strftime('%d/%m/%Y'), class: 'col-xs-12 text-center' }, wrapper_html: { class: 'col-xs-5 col-sm-4' } %>
      <div class="form-group col-xs-2">
        <%= f.button :submit, 'Filtrar', { class: 'btn btn-primary btn-sm' } %>
      </div> 
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-4">
      <h4 class="col-xs-12 label label-<%= get_color_balance(balance_period) %> label-white middle balance-sum">
        Saldo total para o periodo:
        <strong class="time-p text-<%= get_color_balance(balance_period) %>"><%= balance_period.to_s %>
          <i class="fa <%= get_icon_balance(balance_period) %>"></i>
        </strong>
      </h4>
    </div>
    <div class="col-xs-12 col-sm-2 pull-right text-right row">
      <div class="btn-group">
				<button data-toggle="dropdown" class="btn dropdown-toggle" aria-expanded="false">
					Exportar
					<span class="ace-icon fa fa-caret-down icon-on-right"></span>
				</button>
				<ul class="dropdown-menu dropdown-default">
					<li>
            <%= link_to 'Para PDF', export_day_records_path(format: 'pdf', from: from, to: to) %>
					</li>
          <li>
            <%= link_to 'Para XLSX', export_day_records_path(format: 'xlsx', from: from, to: to) %>
          </li>
				</ul>
			</div>
    </div>
  </div>
</div>

app/views/day_records/_time_record_fields.html.erb
<div class="nested-fields col-xs-12 col-md-2">
  <%= f.input :time, label: false, wrapper_html: { class: 'text-center col-xs-10 col-sm-8', style: 'padding-right: 0;'} do %>
    <span class="text-capitalize entrance-exit">Entrada </span><span class="text-capitalize number-of-type">1</span>
    <%= f.input_field :time, as: :string, class: 'optional form-control timepicker text-center pull-left', value: f.object.time.try(:strftime, "%H:%M") %>
  <% end %>

  <%= link_to_remove_association '<span class="text-danger pull-left" style="margin-top: 20px;"> <i class="fa fa-trash fa-2x"></i></span>'.html_safe, f, class: 'col-xs-2 col-sm-1' %>
</div>

app/views/day_records/edit.html.erb
<%- model_class = DayRecord -%>
<% content_for :page_header do %>
  <h1><%= "#{t('helpers.titles.edit')} #{model_class.model_name.human.titleize}" %></h1>
<% end %>
<%= render 'form', day_record: @day_record %>

app/views/day_records/index.html.erb
<% content_for :page_header do %>
  <h1 class="heading text-left">Relatório de Horas
    <small>
		  <i class="ace-icon fa fa-angle-double-right"></i>
		  Visualize os seus registros de forma fácil
		</small>
    <%= link_to 'Registrar agora', add_now_day_records_path, class: 'btn btn-success btn-sm', method: :post %>
  </h1>
<% end %>
<%= render 'search_range', from: @from, to: @to, balance_period: @balance_period %>
<div class="row">
  <div class="col-xs-12 table-list-container">
    <table class="table table-bordered table-hover table-list-records">
      <thead>
        <tr>
          <th class="text-left col-md-1">Dia</th>
          <% @max_time_records.times do |index| %>
            <th class="text-center col-md-1"><%= get_time_label_from_number(index) %></th>
          <% end %>
          <th class="text-center col-md-1" >Total</th>
          <th class="text-center col-md-1" >Saldo</th>
          <th class="text-center col-md-1" >Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @day_records.each do |day_record| %>
        <tr title="<%= day_record.observations %>">
          <td>
            <h5 class="text-left"><%= l day_record.reference_date, format: :short %>
              <%= display_labor_laws_violations(day_record, current_user.current_account) %>
            </h5>
          </td>
          <% @max_time_records.times do |index| %>
            <td class="text-center">
              <p class="time-p">
                <%= day_record.time_records.try(:[], index).try(:time).try(:to_s, :time) %>
              </p>
            </td>
          <% end %>

          <td class="text-center">
            <p class="time-p">
              <span><%= format_seconds_to_time(day_record.total_worked) %></span>
            </p>
          </td>
          <td class="text-center">
            <p class="time-p text-<%= get_color_balance(day_record.balance) %>">
              <strong><%= day_record.balance %></strong>
              <i class="fa <%= get_icon_balance(day_record.balance) %>"></i>
            </p>
          </td>
          <td class="text-center">
            <%= link_to edit_day_record_path(day_record), class: 'btn btn-primary btn-xs' do %>
              <i class="fa fa-pencil-square-o"></i>
              <%= t('helpers.links.edit') %>
            <% end %>

            <%= link_to day_record_path(day_record), method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-xs btn-danger' do %>
              <i class="fa fa-trash-o"></i>
              <%= t('helpers.links.destroy') %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <div class="box-footer clearfix">
       <%= paginate @day_records %>
    </div>
  </div>
</div>

<script charset="utf-8">
  $(function(){
    moment.locale('pt-br');

    $('#daterange-btn').daterangepicker({
      format: 'DD/MM/YYYY',
      ranges: {
        'Hoje': [moment(), moment()],
        'Ontem': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
        'Últimos 7 dias': [moment().subtract(6, 'days'), moment()],
        'Últimos 30 dias': [moment().subtract(29, 'days'), moment()],
        'Esse mês': [moment().startOf('month'), moment().endOf('month')]
      },
      locale: {
        applyLabel: 'Aplicar',
        cancelLabel: 'Cancelar',
        fromLabel: 'De',
        toLabel: 'Até',
        weekLabel: 'W',
        customRangeLabel: 'Personalizar Data'
      },
      startDate: moment().subtract(29, 'days'),
      endDate: moment()
    },
    function(start, end) {
      $('#date_range_from').val(start.format('DD/MM/YYYY'));
      $('#date_range_to').val(end.format('DD/MM/YYYY'));
    });
  });
</script>

app/views/day_records/new.html.erb
<%- model_class = DayRecord -%>
<% content_for :page_header do %>
  <h1><%= "#{t('helpers.titles.new')} #{model_class.model_name.human.titleize}" %></h1>
<% end %>
<%= render 'form', day_record: @day_record %>