config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }, format: false

  devise_scope :user do
    authenticated :user do
      root to: redirect('/day_records'), as: :authenticated_root

      patch 'change_current_account/:id', to: 'accounts#change_current', format: false, as: :change_current_account

      resources :day_records, except: [:show], format: false do
        collection do
          get 'async_worked_time', action: :async_worked_time
          get 'export', action: :export
          post 'add_now', action: :add_now
        end
      end

      resources :closures, except: [:show], format: false
    end

    unauthenticated do
      root 'site#index', as: :unauthenticated_root
      get '/obrigado', to: 'site#thank_you', as: :thank_you
      post '/contato', to: 'site#contact', as: :contact, format: false
    end
  end
end

app/models/closure.rb
class Closure < ActiveRecord::Base
  belongs_to :account, touch: true

  validates_presence_of :start_date, :end_date

  validates_uniqueness_of :start_date, :end_date, scope: :account_id

  default_scope -> { order(end_date: :desc) }

  def balance
    Rails.cache.fetch("#{cache_key}/balance") do
      account
      .day_records.where(reference_date: start_date..end_date)
      .inject(TimeBalance.new) { |sum_balance, day| sum_balance.sum(day.balance) }
    end
  end
end

app/models/mongo_model/closure.rb
class MongoModel::Closure
  include Mongoid::Document

  store_in collection: "closures"

  field :start_date, type: Date
  field :end_date, type: Date

  belongs_to :account, class_name: MongoModel::Account.to_s

  validates_presence_of :start_date, :end_date

  validates_uniqueness_of :start_date, :end_date, scope: :account_id

  default_scope -> { desc(:end_date) }

  def balance
    account.day_records.where(reference_date: start_date..end_date).
    inject(TimeBalance.new) { |sum_balance, day| sum_balance.sum(day.balance) }
  end
end

app/controllers/closures_controller.rb
class ClosuresController < GenericCrudController

  before_action :find_closure, only: [:edit, :update, :destroy]

  def index
    @closures = current_account.closures.page params[:page]
  end

  def new
    @closure = Closure.new
    @closure.start_date = (Date.current - 3.months)
    @closure.end_date = Date.current
  end

  def create
    @closure = Closure.new(model_params)
    super
  end

  def edit
  end

  def update
    super
  end

  def destroy
    super
  end

  private

  def find_closure
    @closure = current_account.closures.find(closure_id_param)
  end

  def closure_id_param
    params.require(:id)
  end

  def model_params
    params.require(:closure).permit(:start_date, :end_date)
  end
end

app/views/closures/_form.html.erb
<%= simple_form_for closure do |f| %>
<div class="row">
  <%= f.hidden_field :id %>
  <%= f.input :start_date, as: :string, wrapper_html: {class: 'col-xs-4 col-sm-2 col-md-2 text-center'}, input_html: { value: localize(f.object.start_date, format: "%d/%m/%Y"), class: 'datepicker text-center'} %>
  <%= f.input :end_date, as: :string, wrapper_html: {class: 'col-xs-4 col-sm-2 col-md-2 text-center'}, input_html: { value: localize(f.object.end_date, format: "%d/%m/%Y"), class: 'datepicker text-center'} %>
</div>
  <%= f.button :submit %>
<% end %>

app/views/closures/edit.html.erb
<%- model_class = Closure -%>
<% content_for :page_header do %>
  <h1><%= "#{t('helpers.titles.edit')} #{model_class.model_name.human.titleize}" %></h1>
<% end %>
<%= render 'form', closure: @closure %>

app/views/closures/index.html.erb
<% content_for :page_header do %>
  <h1 class="heading text-left">Fechamentos
    <small>
		  <i class="ace-icon fa fa-angle-double-right"></i>
		  Visualize as datas em que foram fechados os seus horários
		</small>
  </h1>
<% end %>
<div style="overflow-x: auto;">
  <table class="table table-bordered table-hover table-list-closures">
    <thead>
      <tr>
        <th class="text-center col-md-1">Data Inicial</th>
        <th class="text-center col-md-1" >Data Final</th>
        <th class="text-center col-md-1" >Saldo</th>
        <th class="text-center col-md-1" >Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @closures.each do |closure| %>
        <tr>
          <td>
            <h5 class="text-center"><%= l closure.start_date, format: :default %></h5>
          </td>
          <td>
            <h5 class="text-center"><%= l closure.end_date, format: :default %></h5>
          </td>
          <td class="text-center">
            <p class="time-p text-<%= get_color_balance(closure.balance) %>">
              <strong><%= closure.balance %></strong>
              <i class="fa <%= get_icon_balance(closure.balance) %>"></i>
            </p>
          </td>
          <td class="text-center">
            <%= link_to edit_closure_path(closure), class: 'btn btn-primary btn-xs' do %>
              <i class="fa fa-pencil-square-o"></i>
              <%= t('helpers.links.edit') %>
            <% end %>

            <%= link_to closure_path(closure), method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-xs btn-danger' do %>
              <i class="fa fa-trash-o"></i>
              <%= t('helpers.links.destroy') %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="box-footer clearfix">
     <%= paginate @closures %>
  </div>
</div>

app/views/closures/new.html.erb
<%- model_class = Closure -%>
<% content_for :page_header do %>
  <h1><%= "#{t('helpers.titles.new')} #{model_class.model_name.human.titleize}" %></h1>
<% end %>
<%= render 'form', closure: @closure %>