config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }, format: false

  devise_scope :user do
    authenticated :user do
      root to: redirect('/day_records'), as: :authenticated_root

      patch 'change_current_account/:id', to: 'accounts#change_current', format: false, as: :change_current_account

      resources :day_records, except: [:show], format: false do
        collection do
          get 'async_worked_time', action: :async_worked_time
          get 'export', action: :export
          post 'add_now', action: :add_now
        end
      end

      resources :closures, except: [:show], format: false
    end

    unauthenticated do
      root 'site#index', as: :unauthenticated_root
      get '/obrigado', to: 'site#thank_you', as: :thank_you
      post '/contato', to: 'site#contact', as: :contact, format: false
    end
  end
end

app/views/layouts/_flash_messages.html.erb
<% unless flash.empty? %>
  <% flash.each do |type, msg| %>
    <div class="alert alert-<%= flash_class(type) %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        <i class="ace-icon fa fa-times"></i>
      </button>
      <strong>
        <i class="ace-icon fa <%= flash_icon(type) %>"></i>
    	</strong>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meu Controle de Ponto</title>
  <%= render partial: 'shared/favicons' %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300" />
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <% yield :page_styles %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'ajax_update' %>
  <%= csrf_meta_tags %>
</head>
<body class ="no-skin">
<div id="navbar" class="navbar navbar-default">

			<div class="navbar-container" id="navbar-container">

				<button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
					<span class="sr-only">Toggle sidebar</span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>

					<span class="icon-bar"></span>
				</button>

				<div class="navbar-header pull-left">
					<a href="/" class="navbar-brand">
            <small>
              <span class="fa-stack fa-lg">
                <i class="fa fa-calendar-o fa-stack-2x"></i>

                <i class="fa fa-clock-o" style="right: 6px; bottom: 3px; position: absolute;"></i>
              </span>
            </small>
							Meu Controle de Ponto
					</a>
				</div>

				<div class="navbar-buttons navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">
          <li class="green">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="false">
                <span class="badge badge-success"><%= current_user.current_account.name %></span>
                <i class="fa fa-retweet fa-2x"></i>
              </a>

              <ul class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
                <li class="dropdown-header">
                  Selecione a conta para trocar
                </li>

                <li class="dropdown-content">
                  <ul class="dropdown-menu dropdown-navbar">
                    <% current_user.accounts.each do |account| %>
                      <li>
                        <%= link_to change_current_account_path(account.id), method: :patch do %>

                          <p class="text-center lead account-chooser-item">
                            <% if account == current_user.current_account %>
                              <i class="fa fa-check text-success"></i>
                            <% end %>
                            <%= account.name %>
                          </p>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </li>

                <li class="dropdown-footer">
                  <%= link_to edit_user_registration_path do %>
                    <i class="ace-icon fa fa-cog"></i>
                    Ir para <b>Configurações</b>
                  <% end %>                                    
                </li>
              </ul>
            </li>
						<li class="light-blue">
							<a data-toggle="dropdown" href="#" class="dropdown-toggle">
								<span class="user-info">
									<small>Olá,</small>
									<%= current_user.first_name %>
								</span>

								<i class="ace-icon fa fa-caret-down"></i>
							</a>

							<ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
								<li>
                  <%= link_to edit_user_registration_path do %>
										<i class="ace-icon fa fa-cog"></i>
										Configurações
                  <% end %>
								</li>

								<li class="divider"></li>

								<li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
										<i class="ace-icon fa fa-power-off"></i>
										Logout
                  <% end %>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</div><!-- /.navbar-container -->
		</div>

app/views/layouts/_navbar.html.erb
<div id="sidebar" class="sidebar responsive" data-sidebar="true" data-sidebar-scroll="true" data-sidebar-hover="true">
	<ul class="nav nav-list" style="top: 0px;">

		<li class="active open">
			<a href="#" >
				<i class="menu-icon fa fa-list"></i>
				<span class="menu-text"> Registros </span>

				<b class="arrow fa fa-angle-down"></b>
			</a>

			<b class="arrow"></b>

			<ul class="submenu">
				<li class="<%= 'active' if current_page?(day_records_path) || current_page?(authenticated_root_path) %>">
          <%= link_to day_records_path do %>
            <i class="menu-icon fa fa-caret-right"></i>
            Relatório
          <% end %>

					<b class="arrow"></b>
				</li>

				<li class="<%= 'active' if current_page?(new_day_record_path) %>">
          <%= link_to new_day_record_path do %>
            <i class="menu-icon fa fa-caret-right"></i>
            Novo Registro
          <% end %>

					<b class="arrow"></b>
				</li>
			</ul>
		</li>
		<li class="active open">
			<a href="#" >
				<i class="menu-icon fa fa-archive"></i>
				<span class="menu-text"> Fechamentos </span>

				<b class="arrow fa fa-angle-down"></b>
			</a>

			<b class="arrow"></b>

			<ul class="submenu">
				<li class="<%= 'active' if current_page?(closures_path) %>">
          <%= link_to closures_path do %>
            <i class="menu-icon fa fa-caret-right"></i>
            Listar
          <% end %>

					<b class="arrow"></b>
				</li>

				<li class="<%= 'active' if current_page?(new_closure_path) %>">
          <%= link_to new_closure_path do %>
            <i class="menu-icon fa fa-caret-right"></i>
            Novo Fechamento
          <% end %>

					<b class="arrow"></b>
				</li>
			</ul>
		</li>
	</ul><!-- /.nav-list -->
	<div class="navbar-footer">
		<div class="infobox <%= get_dashboard_color(@dashboard.total_balance) %>">
			<div class="infobox-icon">
				<i class="ace-icon fa <%= get_icon_balance(@dashboard.total_balance) %>"></i>
			</div>
			<div class="infobox-data">
				<span class="infobox-data-number"><%= @dashboard.total_balance.to_s %></span>
				<div class="infobox-content">Saldo de horas
					<a class="balance-info" tabindex="0" role="button" data-toggle="popover" data-trigger="focus" data-content="O Saldo de horas é contabilizado à partir do seu último Fechamento informado." title="Saldo de horas">
						<i class="fa fa-question-circle"></i>
					</a>
				</div>
			</div>
		</div>

		<div class="infobox infobox-blue">
			<div class="infobox-icon">
				<i class="ace-icon fa fa-user"></i>
			</div>

			<div class="infobox-data">
				<span class="infobox-data-number"><%= current_user.workload.to_s(:time) %></span>
				<div class="infobox-content">Jornada de trabalho</div>
			</div>
		</div>

		<div class="infobox infobox-pink">
			<div class="infobox-icon">
				<i class="ace-icon fa fa-sign-out"></i>
			</div>

			<div class="infobox-data">
				<span class="infobox-data-number"><%= @dashboard.departure_time.to_s(:time) %></span>
				<div class="infobox-content">Previsão de saída
					<a class="departure-info" tabindex="0" role="button" data-toggle="popover" data-trigger="focus" data-content="A previsão de saída utiliza o tempo médio de almoço que você informar nas configurações, enquanto você não registrar uma Entrada 2." title="Previsão de saída">
						<i class="fa fa-question-circle"></i>
					</a>
				</div>
			</div>
		</div>

		<div class="infobox infobox-blue2">
			<div class="infobox-progress">
				<div class="easy-pie-chart percentage" data-percent="<%= @dashboard.percentage_worked %>" data-size="60" style="height: 60px; width: 60; line-height: 58px;">
					<span class="percent"><%= @dashboard.percentage_worked %></span>%
				<canvas height="60" width="60"></canvas></div>
			</div>

			<div class="infobox-data">
				<span class="infobox-data-number info-worked-time"><%= @dashboard.total_worked.to_s(:time) %></span>

				<div class="infobox-content">Total de hoje</div>
			</div>
		</div>

		<% if current_user.warn_rest_period %>
			<div class="infobox infobox-orange2">
				<div class="infobox-icon">
					<i class="ace-icon fa fa-sign-in"></i>
				</div>

				<div class="infobox-data">
					<span class="infobox-data-number"><%= @dashboard.next_entrance_time.try(:to_s, :time) || '--:--' %></span>
					<div class="infobox-content">Próxima Entrada
						<a class="departure-info" tabindex="0" role="button" data-toggle="popover" data-trigger="focus" data-content="Esta é sua próxima entrada recomendada para não infrigir o Art. 66 da CLT." title="Próxima Entrada">
							<i class="fa fa-question-circle"></i>
						</a>
					</div>
				</div>
			</div>
		<% end %>
	</div>

</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" class="sidebar responsive" data-sidebar="true" data-sidebar-scroll="true" data-sidebar-hover="true">
	<ul class="nav nav-list" style="top: 0px;">

		<li class="active open">
			<a href="#" >
				<i class="menu-icon fa fa-list"></i>
				<span class="menu-text"> Registros </span>

				<b class="arrow fa fa-angle-down"></b>
			</a>

			<b class="arrow"></b>

			<ul class="submenu">
				<li class="<%= 'active' if current_page?(day_records_path) || current_page?(authenticated_root_path) %>">
          <%= link_to day_records_path do %>
            <i class="menu-icon fa fa-caret-right"></i>
            Relatório
          <% end %>

					<b class="arrow"></b>
				</li>

				<li class="<%= 'active' if current_page?(new_day_record_path) %>">
          <%= link_to new_day_record_path do %>
            <i class="menu-icon fa fa-caret-right"></i>
            Novo Registro
          <% end %>

					<b class="arrow"></b>
				</li>
			</ul>
		</li>
		<li class="active open">
			<a href="#" >
				<i class="menu-icon fa fa-archive"></i>
				<span class="menu-text"> Fechamentos </span>

				<b class="arrow fa fa-angle-down"></b>
			</a>

			<b class="arrow"></b>

			<ul class="submenu">
				<li class="<%= 'active' if current_page?(closures_path) %>">
          <%= link_to closures_path do %>
            <i class="menu-icon fa fa-caret-right"></i>
            Listar
          <% end %>

					<b class="arrow"></b>
				</li>

				<li class="<%= 'active' if current_page?(new_closure_path) %>">
          <%= link_to new_closure_path do %>
            <i class="menu-icon fa fa-caret-right"></i>
            Novo Fechamento
          <% end %>

					<b class="arrow"></b>
				</li>
			</ul>
		</li>
	</ul><!-- /.nav-list -->
	<div class="navbar-footer">
		<%= render 'accounts/sidebar_widget', account_presenter: account_presenter %>
	</div>

</div>

app/views/layouts/application.html.erb
<%= render partial: 'layouts/header' %>

<div class="main-container" id="main-container">
  <%= render 'layouts/sidebar', account_presenter: @account_presenter %>
  <div class="main-content">
    <div class="main-content-inner">
			</div>
      <div class="page-content">
        <%= render 'layouts/flash_messages' %>
        <div class="page-header">
          <%= yield :page_header %>
    		</div>
        <div class="row">
          <div class="col-xs-12" >
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meu Controle de Ponto</title>
  <%= render partial: 'shared/favicons' %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,300" />
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <% yield :page_styles %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <%= render partial: 'shared/analytics_script' %>
</head>
<body class="login-layout light-login">
<div class="main-container">
	<div class="main-content">
		<div class="row">
			<div class="col-sm-10 col-sm-offset-1">
				<div class="login-container">
					<div class="center">
						<h1>
							<span class="grey">
                <small>
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-calendar-o fa-stack-2x"></i>

                    <i class="fa fa-clock-o" style="right: 6px; bottom: 3px; position: absolute;"></i>
                  </span>
                </small>
                Meu Controle de Ponto</span>
						</h1>
					</div>

					<div class="space-6"></div>

					<div class="position-relative">
						<%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Controle de Ponto" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>
  </body>
</html>